# Generated by Django 4.2.5 on 2023-11-17 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fen", "0003_remove_item_split_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="receipt",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="fen.receipt"
            ),
        ),
    ]
